(defn git_pull [] [(import os) (os.system "git pull")])
(defn git_force_pull [] [(import os) (os.system "git fetch --all") (os.system "git reset --hard origin/master")])
(defn ping [host] (nth [(import commands)(nth (commands.getstatusoutput (+ "ping -c1 " host)) 1)] 1))
(defn join_room [s room] (s.send (% "JOIN %s\r\n" room))) 
(defn add_two [x] (+ x 2))
(defn add_three [x] (+ x 3))
(defn add_five [x] (add_two (add_three x)))
(defn add_four [x] (add_two (add_two x)))
(defn add_six [x] (+ x 6) ) 